# Generated by Django 4.2.4 on 2023-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_rozarpay_order_id_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='customer',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Cancel', 'Cancel'), ('Deliverd', 'Delivered')], default='Pending', max_length=55),
        ),
    ]
